[id]
name = spl_process_tree_lab
version = 1.0.4

[install]
is_configured = 0
state = enabled

[package]
id = spl_process_tree_lab
check_for_updates = false

[ui]
is_visible = 1
label = Process Tree Lab

[launcher]
author = G0TH3R
description = Bounded process relationship analysis across selectable Splunk data sources.
version = 1.0.4

[triggers]
reload.nav = simple
reload.ui = simple
reload.metadata = simple
reload.macros = simple
